/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.emergya.negocio.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LineaDeFactura service. Represents a row in the &quot;lineaDeFactura&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.emergya.negocio.model.impl.LineaDeFacturaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.emergya.negocio.model.impl.LineaDeFacturaImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a linea de factura model instance should use the {@link LineaDeFactura} interface instead.
 * </p>
 *
 * @author adiaz
 * @see LineaDeFactura
 * @see es.emergya.negocio.model.impl.LineaDeFacturaImpl
 * @see es.emergya.negocio.model.impl.LineaDeFacturaModelImpl
 * @generated
 */
public interface LineaDeFacturaModel extends BaseModel<LineaDeFactura> {
	/**
	 * Gets the primary key of this linea de factura.
	 *
	 * @return the primary key of this linea de factura
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this linea de factura
	 *
	 * @param pk the primary key of this linea de factura
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the linea deactura id of this linea de factura.
	 *
	 * @return the linea deactura id of this linea de factura
	 */
	public long getLineaDeacturaId();

	/**
	 * Sets the linea deactura id of this linea de factura.
	 *
	 * @param lineaDeacturaId the linea deactura id of this linea de factura
	 */
	public void setLineaDeacturaId(long lineaDeacturaId);

	/**
	 * Gets the detalle of this linea de factura.
	 *
	 * @return the detalle of this linea de factura
	 */
	@AutoEscape
	public String getDetalle();

	/**
	 * Sets the detalle of this linea de factura.
	 *
	 * @param detalle the detalle of this linea de factura
	 */
	public void setDetalle(String detalle);

	/**
	 * Gets the importe of this linea de factura.
	 *
	 * @return the importe of this linea de factura
	 */
	public double getImporte();

	/**
	 * Sets the importe of this linea de factura.
	 *
	 * @param importe the importe of this linea de factura
	 */
	public void setImporte(double importe);

	/**
	 * Gets the factura id of this linea de factura.
	 *
	 * @return the factura id of this linea de factura
	 */
	public long getFacturaId();

	/**
	 * Sets the factura id of this linea de factura.
	 *
	 * @param facturaId the factura id of this linea de factura
	 */
	public void setFacturaId(long facturaId);

	/**
	 * Gets a copy of this linea de factura as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public LineaDeFactura toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(LineaDeFactura lineaDeFactura);

	public int hashCode();

	public String toString();

	public String toXmlString();
}